name: Deploy From GitHub to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install deps if missing
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io git-lfs
              sudo systemctl enable docker
              sudo systemctl start docker
              git lfs install
            fi

            # Clone or update repo
            if [ ! -d "/home/${USER}/app/.git" ]; then
              git clone https://github.com/Amadabh/image-caption.git /home/${USER}/app
            else
              cd /home/${USER}/app && git pull
            fi

            # Ensure LFS files are pulled
            cd /home/${USER}/app
            git lfs pull

            # Rebuild + restart container
            sudo docker build -t myapp .
            sudo docker stop myapp-container || true
            sudo docker rm myapp-container || true
            sudo docker run -d --name myapp-container -p 8000:8000 -p 8501:8501 myapp
